### ISSUE TITLE
Modificar y poner en funcionamiento el responsive en todo el sitio.

### ISSUE THREAD

**Issue by Amadeo-G** [FacKuSalvatierra/Aerolineas-ISPC#30]
Se asigna a Elías la tarea de revisar y modificar el diseño responsivo de todo el sitio web,

**Comment by eliasgiannantonio** [comment]
El diseño responsive ha sido implementado en todos los documentos HTML. Con el agregado de CSS Grid y Media queries se ha establecido un diseño adaptable y accesible para diferentes dispositivos y resoluciones.
