### ISSUE TITLE
Funcionalidad JavaScript en formularios

### ISSUE THREAD

**Issue by Amadeo-G** [FacKuSalvatierra/Aerolineas-ISPC#33]
Se le encomienda a Elías la revisión y la implementación de la funcionalidad JavaScript en los formularios (login, registro).

**Comment by eliasgiannantonio** [comment]
Funcionalidad Javascript agregada en la sección de Inicio de Sesión y Registro. En el mismo script se especifica que el usuario debe completar el relleno de campos importantes como el Nombre, Correo, Contraseña, Confirmaciones de contraseña...
