### ISSUE TITLE
Fotos de los integrantes

### ISSUE THREAD

**Issue by Amadeo-G** [FacKuSalvatierra/Aerolineas-ISPC#40]
Se le asigna a Enzo la tarea de compilar las fotos de cada integrante del equipo para insertarlas en la página "Quienes somos".

**Comment by Amadeo-G** [comment]
Foto enviada y recibida por Enzo.

**Comment by FacKuSalvatierra** [comment]
Foto enviada y recibida por Enzo tambien el link de mi perfil de Linkedin

**Comment by eliasgiannantonio** [comment]
Foto enviada y recibida por Enzo, también adjunté mi enlace de perfil de LinkedIn.
